### ISSUE TITLE
用户脚本交易

### ISSUE THREAD

**Issue by JingMatrix** [WhiteSevs/TamperMonkeyScript#1]
你好！我想问一下你有过售卖自己脚本的想法吗？我在考虑建造一个平台让开发者可以在上面售卖其脚本，并提供一定的维护服务。所以我想了解一些脚本开发者对交易脚本的想法。

如果感兴趣的话，可以进一步私聊：jingmatrix@gmail.com 或者 https://t.me/jianyuma

**Comment by WhiteSevs** [comment]
暂无脚本售卖的想法

**Comment by JingMatrix** [comment]
了解了，谢谢。
