### ISSUE TITLE
贴吧回复显示Null问题

### ISSUE THREAD

**Issue by mpamxl** [WhiteSevs/TamperMonkeyScript#11]
### 先决条件

- [X] 我使用的是**本仓库**最新版本的油猴脚本
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**

### 脚本运行的容器

Via浏览器

### 脚本名称

【移动端】百度系优化

### 问题描述

![Screenshot_20240417-072021_Via](https://github.com/WhiteSevs/TamperMonkeyScript/assets/5687454/cd3d62c9-c6b2-4b9a-95cd-2e87afc04551)
![Screenshot_20240417-072035_Via](https://github.com/WhiteSevs/TamperMonkeyScript/assets/5687454/06344352-a0b0-4510-9809-ef1b87205454)

**Comment by mpamxl** [comment]
https://tieba.baidu.com/p/510817845
附上测试链接

**Comment by mpamxl** [comment]
![Screenshot_20240417-075352_Via.jpg](https://github.com/WhiteSevs/TamperMonkeyScript/assets/5687454/f2f2b978-755e-4047-8574-e2a1d7508aa7)

同时这个链接出现评论请求超时错误
https://tieba.baidu.com/p/5804290837?pid=149613297819&cid=0#/comment-anchor

**Comment by mpamxl** [comment]
![Screenshot_20240417-075619_Via.jpg](https://github.com/WhiteSevs/TamperMonkeyScript/assets/5687454/9c31ff60-0415-440b-8be4-de31b4c3d7ba)

以及点击搜索字体变成竖向，不点击时正常

**Comment by WhiteSevs** [comment]
![Clip_2024-04-17_11-49-25](https://github.com/WhiteSevs/TamperMonkeyScript/assets/50544447/0e6a54e4-6eba-4ef4-aaf6-ccca00f4a145)

这种末尾是`�`是百度贴吧的`该楼层疑似违规已被系统折叠`，现已修复

`undefined`可能是你刷贴吧请求频繁了

`搜索`竖向是浏览器的宽度触发了输入框的最小宽度，现已把输入框的最小宽度设定为`80px`

**Comment by mpamxl** [comment]
好的，还有个问题就是点搜索后只是弹出搜索框，没有自动打开键盘，按理说一般点搜索弹出搜索框应该就对应键盘弹出输入文字搜索了
