### ISSUE TITLE
贴吧搜索后输入法不消失问题

### ISSUE THREAD

**Issue by mpamxl** [WhiteSevs/TamperMonkeyScript#12]
### 先决条件

- [X] 我使用的是**本仓库**最新版本的油猴脚本
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**

### 脚本运行的容器

Via浏览器

### 脚本名称

【移动端】百度系优化

### 问题描述

RT，贴吧点击搜索弹出输入法，输入内容点击搜索后应该关闭输入法窗口，再点击搜索框再出现，而现在搜索后输入法窗口一直存在结果界面。

**Comment by WhiteSevs** [comment]
https://github.com/WhiteSevs/TamperMonkeyScript/commit/df7162a25ad6c6facb24ea89c0bbc795e7517757
已修复
