### ISSUE TITLE
贴吧搜索问题

### ISSUE THREAD

**Issue by mpamxl** [WhiteSevs/TamperMonkeyScript#13]
### 先决条件

- [X] 我使用的是**本仓库**最新版本的油猴脚本
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**

### 脚本运行的容器

Via浏览器

### 脚本名称

【移动端】百度系优化

### 问题描述

除了tieba.baidu.com的链接可以搜索内容，nba.baidu和static.tieba.baidu搜索都一直转圈没有结果，不知是否Bug，辛苦大佬修复。最近我好像反馈的有点多...

**Comment by WhiteSevs** [comment]
Via有个问题，使用跨域请求返回`GBK`编码的内容时，via不会给编码为`GBK`，从而导致获取的内容都是乱码，反馈了很久了没修复，所以用的`fetch`请求

`搜索都一直转圈没有结果`这个问题的话后面加个选项让贴吧域名自动跳转至`tieba.baidu.com`

**Comment by mpamxl** [comment]
我去给作者反馈下，你意思让其它贴吧链接都跳转到固定这个吗？

**Comment by WhiteSevs** [comment]
> 我去给作者反馈下，你意思让其它贴吧链接都跳转到固定这个吗？

对，百度贴吧的域名自动跳转至`tieba.baidu.com`

**Comment by mpamxl** [comment]
> > 我去给作者反馈下，你意思让其它贴吧链接都跳转到固定这个吗？
> 
> 对，百度贴吧的域名自动跳转至`tieba.baidu.com`

也不失一个办法，不过如果Via能解决上面的问题是不是就不用了？

**Comment by WhiteSevs** [comment]
> > > 我去给作者反馈下，你意思让其它贴吧链接都跳转到固定这个吗？
> > 
> > 
> > 对，百度贴吧的域名自动跳转至`tieba.baidu.com`
> 
> 也不失一个办法，不过如果Via能解决上面的问题是不是就不用了？



不光这个，via的Cookie问题也没解决

**Comment by mpamxl** [comment]
![Screenshot_20240418-175153_Via.jpg](https://github.com/WhiteSevs/TamperMonkeyScript/assets/5687454/f9d1f3b2-d395-457d-b4d6-b111b25c2595)

出现这个问题

**Comment by mpamxl** [comment]
> > > > 我去给作者反馈下，你意思让其它贴吧链接都跳转到固定这个吗？
> > > 
> > > 
> > > 对，百度贴吧的域名自动跳转至`tieba.baidu.com`
> > 
> > 也不失一个办法，不过如果Via能解决上面的问题是不是就不用了？
> 
> 
> 
> 不光这个，via的Cookie问题也没解决

Cookie什么问题？我也跟他说下

**Comment by WhiteSevs** [comment]
这种不建议在非`tieba.baidu.com`域名下使用，`static.tieba.baidu.com`这个域名的`https`证书都没有，其它的百度类域名建议开启`自动重定向至主域名`直接重定向，保不齐其它域名的Api请求会有什么问题出现

Cookie是`GM_xmlhttpRequest`没有自动发送Cookie，估计Via作者不会加这个功能，因为有安全风险

**Comment by mpamxl** [comment]
> 这种不建议在非`tieba.baidu.com`域名下使用，`static.tieba.baidu.com`这个域名的`https`证书都没有，其它的百度类域名建议开启`自动重定向至主域名`直接重定向，保不齐其它域名的Api请求会有什么问题出现
> 
> Cookie是`GM_xmlhttpRequest`没有自动发送Cookie，估计Via作者不会加这个功能，因为有安全风险

也就是说脚本这边现在没法直接重定向吗？Cookie问题我问问他看

**Comment by WhiteSevs** [comment]
脚本已添加这个重定向功能了，默认关闭状态，在设置里开启就行
