### ISSUE TITLE
最新重构脚本贴吧失效

### ISSUE THREAD

**Issue by mpamxl** [WhiteSevs/TamperMonkeyScript#15]
### 先决条件

- [X] 我使用的是**本仓库**最新版本的油猴脚本
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**

### 脚本运行的容器

Via浏览器

### 脚本名称

【移动端】百度系优化

### 问题描述

新的重构脚本贴吧完全失效，也没法进设置

**Comment by mpamxl** [comment]
> 对，Via没适配，X浏览器正常
> 新版加了个贴吧的个人主页重构，删除了一个百度搜索的拦截规则，不更新也没问题，直接回退4月的版本手动修改版本号就行

了解，那我暂时先回退下，或者可以把贴吧部分的个人主页重构代码单独提出来加进去旧版吗？

**Comment by WhiteSevs** [comment]
不太行，加不进去

**Comment by mpamxl** [comment]
> 不太行，加不进去

了解，那我先暂用旧版吧，那假如新版我想剔除其它不用的内容是不是也不好弄了？

**Comment by WhiteSevs** [comment]
> > 不太行，加不进去
> 
> 了解，那我先暂用旧版吧，那假如新版我想剔除其它不用的内容是不是也不好弄了？

简单的话就是按照之前说的修改脚本的@match为需要的，复杂的话需要自己下载源码，构建脚本

**Comment by mpamxl** [comment]
> > > 不太行，加不进去
> > 
> > 了解，那我先暂用旧版吧，那假如新版我想剔除其它不用的内容是不是也不好弄了？
> 
> 简单的话就是按照之前说的修改脚本的@match为需要的，复杂的话需要自己下载源码，构建脚本

了解，请问源码可从哪里下载？

**Comment by WhiteSevs** [comment]
就是本仓库，`【移动端】百度系优化`在`./packages/【移动端】百度系优化`下

**Comment by WhiteSevs** [comment]
> > 就是本仓库，`【移动端】百度系优化`在`./packages/【移动端】百度系优化`下
> 
> 感谢，请问Mini和正常的有啥区别呢

min是压缩过的

**Comment by mpamxl** [comment]
好的，再请问下最近遇到提示触发百度验证，但弹出的验证已经过了评论区还是显示这个，怎么解决呢？

**Comment by WhiteSevs** [comment]
> 好的，再请问下最近遇到提示触发百度验证，但弹出的验证已经过了评论区还是显示这个，怎么解决呢？

开启`实验性-请求携带cookie`，或者换个能安装`篡改猴`或`暴力猴`或`脚本猫`扩展的浏览器看

**Comment by mpamxl** [comment]
> > 好的，再请问下最近遇到提示触发百度验证，但弹出的验证已经过了评论区还是显示这个，怎么解决呢？
> 
> 开启`实验性-请求携带cookie`，或者换个能安装`篡改猴`或`暴力猴`或`脚本猫`扩展的浏览器看

好的，我试试，顺便Via那边我跟作者说了，开玩笑回话，我要吐槽这个脚本，这脚本也太夸张了吧。明明就是个改百度页面的小脚本，可是却像个前端项目一样，依赖多的一批。我不知道到底是什么需求，要让这个脚本使用 vue + vue router + vue element plus + vue element plus icons，哈哈

**Comment by WhiteSevs** [comment]
> > > 好的，再请问下最近遇到提示触发百度验证，但弹出的验证已经过了评论区还是显示这个，怎么解决呢？
> > 
> > 
> > 开启`实验性-请求携带cookie`，或者换个能安装`篡改猴`或`暴力猴`或`脚本猫`扩展的浏览器看
> 
> 好的，我试试，顺便Via那边我跟作者说了，开玩笑回话，我要吐槽这个脚本，这脚本也太夸张了吧。明明就是个改百度页面的小脚本，可是却像个前端项目一样，依赖多的一批。我不知道到底是什么需求，要让这个脚本使用 vue + vue router + vue element plus + vue element plus icons，哈哈

其实就是百度贴吧个人主页的页面用到了，其它的地方没有用到，也就4个库

**Comment by mpamxl** [comment]
> > > > 好的，再请问下最近遇到提示触发百度验证，但弹出的验证已经过了评论区还是显示这个，怎么解决呢？
> > > 
> > > 
> > > 开启`实验性-请求携带cookie`，或者换个能安装`篡改猴`或`暴力猴`或`脚本猫`扩展的浏览器看
> > 
> > 好的，我试试，顺便Via那边我跟作者说了，开玩笑回话，我要吐槽这个脚本，这脚本也太夸张了吧。明明就是个改百度页面的小脚本，可是却像个前端项目一样，依赖多的一批。我不知道到底是什么需求，要让这个脚本使用 vue + vue router + vue element plus + vue element plus icons，哈哈
> 
> 其实就是百度贴吧个人主页的页面用到了，其它的地方没有用到，也就4个库

贴吧是不是即使登录了也没法回复？

**Comment by WhiteSevs** [comment]
对，不能回复/评论

**Comment by mpamxl** [comment]
> 对，不能回复/评论

这就尴尬了，那登录和不登陆就没啥意义了吗？

**Comment by WhiteSevs** [comment]
beta版已可以使用，正式版等待更新
