### ISSUE TITLE
[Bug] <github页面响应慢>

### ISSUE THREAD

**Issue by physxz** [WhiteSevs/TamperMonkeyScript#19]
### 先决条件

- [X] 我使用的是**本仓库**最新版本的油猴脚本
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**

### 脚本运行的容器

扩展-篡改猴（TamperMonkey）

### 脚本名称

网盘链接识别

### 问题描述

GitHub页面点击无响应/响应变慢（5-10s才会反应）

**Comment by WhiteSevs** [comment]
哪个页面？

**Comment by physxz** [comment]
应该是所有的。不是网速或VPN造成的，油管响应很快，但是只要打开github就会变慢，github里边的所有页面都是

WhiteSev ***@***.***> 于2024年5月13日周一 20:47写道：

**Comment by WhiteSevs** [comment]
github页面启用了CSP策略，所以页面的字符串`match`行为会由`Worker`多线程匹配处理变为`单线程`进行匹配，页面内容多的话会阻塞页面加载，最好直接把github的域名排除
