### ISSUE TITLE
[Bug] 非常卡 

### ISSUE THREAD

**Issue by superen7527** [WhiteSevs/TamperMonkeyScript#2]
### 先决条件

- [X] 我使用的是**本仓库**最新版本的油猴脚本
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**

### 使用的脚本名称

手机调试 

### 脚本运行的容器

扩展-暴力猴（Violentmonkey）

### 问题描述

哥们 kiwi上用，进github非常卡，把脚本关了就不卡了。进github刷新后退进网页都要好几秒不能动。是每次都请求网络脚本吗？

**Comment by WhiteSevs** [comment]
`网页调试`这个脚本？代码里没涉及网络请求，但是那几个库`eruda`、`vconsole`、`pageSpy`是有监控网络请求的

**Comment by WhiteSevs** [comment]
`网页调试`这个脚本不涉及什么日志，你可以装篡改猴这个扩展试一下，我用kiwi+篡改猴beta+网页调试没有卡顿的情况，另外设置里的eruda的插件没有全关掉？

**Comment by WhiteSevs** [comment]
这种没什么好办法，`VConsole`是最容易简单使用
