### ISSUE TITLE
学习

### ISSUE THREAD

**Issue by lvjiaj** [WhiteSevs/TamperMonkeyScript#20]
### 先决条件

- [X] 我已经在[这里](https://github.com/WhiteSevs/TamperMonkeyScript/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**

### 脚本名称

抖音优化

### 描述

大佬可以开源一下抖音优化的源代码吗?我想学习一下

**Comment by WhiteSevs** [comment]
在`/packages/`下

**Comment by WhiteSevs** [comment]
> 大佬, 抖音一开启控制台`CPU`就会很高, 如何解决?

无解
