### ISSUE TITLE
抖音优化-iOS Safari无法打开设置.如果能在网页版添加一个按钮就好了

### ISSUE THREAD

**Issue by androidcn** [WhiteSevs/TamperMonkeyScript#21]
### 先决条件

- [X] 我使用的是**本仓库**最新版本的油猴脚本
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**

### 脚本运行的容器

其它

### 扩展版本

最新

### 脚本名称

抖音优化

### 问题描述

抖音优化-iOS Safari 配合 userscript 无法打开设置.如果能在网页版添加一个按钮就好了，最好能把 使用app打开提示隐藏 感谢
![Image](https://github.com/WhiteSevs/TamperMonkeyScript/assets/271715/ca62d4f5-853c-4d28-a6fd-1173b3d95fee)

**Comment by WhiteSevs** [comment]
关于脚本设置菜单
https://github.com/quoid/userscripts/issues/230

你其实可以用stay或者其它脚本管理器，它们应该实现了脚本菜单功能

**Comment by WhiteSevs** [comment]
你的useragent是什么，我测试没显示上面的 open in then 抖音 app

**Comment by androidcn** [comment]
Safari 配合 userscript

**Comment by WhiteSevs** [comment]
测试不出来，没有苹果系的设备，也许你可以试试可以标记元素的拦截广告的插件（如adguard或adblock），看看它是否是一个元素

**Comment by androidcn** [comment]
> 测试不出来，没有苹果系的设备，也许你可以试试可以标记元素的拦截广告的插件（如adguard或adblock），看看它是否是一个元素
我查了查了一下资料
open in app 用了这个meta标签 
估计删掉 name 属性为 apple-itunes-app meta 标签可破

`<meta name="apple-itunes-app" content="app-id=myAppStoreID, app-argument=myURL">`

**Comment by WhiteSevs** [comment]
https://github.com/WhiteSevs/TamperMonkeyScript/blob/dev/packages/%E6%8A%96%E9%9F%B3%E4%BC%98%E5%8C%96/dist/%E6%8A%96%E9%9F%B3%E4%BC%98%E5%8C%96.user.js

试试看是否成功
