### ISSUE TITLE
闲鱼网页版推出来了脚本搞起

### ISSUE THREAD

**Issue by androidcn** [WhiteSevs/TamperMonkeyScript#23]
### 先决条件

- [X] 我已经在[这里](https://github.com/WhiteSevs/TamperMonkeyScript/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**

### 脚本名称

其它(请在下方填写脚本名称)

### 描述

闲鱼网页版
www.Goofish.com
屏蔽广告，过滤关键字，优化排版

### 可能的解决方案

感谢

**Comment by WhiteSevs** [comment]
咸鱼网页版还是初期的吧，功能不多也没广告，脚本有啥使用场景吗？

**Comment by androidcn** [comment]
> 咸鱼网页版还是初期的吧，功能不多也没广告，脚本有啥使用场景吗？

屏蔽广告，目前初期版本，还没放广告，后期肯定会加入目前移动端的广告条目混在搜索结果

设置本地标题关键字黑名单，用户黑名单，直接过滤

优化移动排版显示，例如折叠屏手机，或者iPhone Safari，其实真的受够了咸鱼app体验

**Comment by WhiteSevs** [comment]
移动端排版？我手机试了下，咸鱼还没网页版的移动端吧

**Comment by androidcn** [comment]
> 移动端排版？我手机试了下，咸鱼还没网页版的移动端吧

移动端 他们想要转移到app…放广告
网页版只会有桌面端，得发挥我们创造力，把它适配到移动浏览器😂
