### ISSUE TITLE
[Bug] <Youtube页面卡死>

### ISSUE THREAD

**Issue by PJUNYE** [WhiteSevs/TamperMonkeyScript#24]
### 先决条件

- [X] 我使用的是**本仓库**最新版本的油猴脚本
- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**

### 脚本运行的容器

扩展-篡改猴（TamperMonkey）

### 扩展版本

Chrome PC 篡改猴 5.1.1

### 脚本名称

网盘链接识别

### 问题描述

脚本v2024.8.2
Youtube页面卡顿，卡死，禁用脚本后恢复正常

**Comment by WhiteSevs** [comment]
装一个禁用`CSP`的插件并开启就行
[https://github.com/lisonge/Disable-CSP](https://github.com/lisonge/Disable-CSP)
或者排除掉`youtube.com`
