### ISSUE TITLE
最近百度好像调整了校验偶尔弹窗

### ISSUE THREAD

**Issue by mpamxl** [WhiteSevs/TamperMonkeyScript#26]
### 先决条件

- [X] 我使用的是**本仓库**最新版本的油猴脚本
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**

### 脚本运行的容器

Via浏览器

### 脚本名称

【移动端】百度系优化

### 问题描述

最近偶尔会出现弹窗，界面跟以前好像有所调整，是不是百度调整了校验，请看下能否修复。
![Screenshot_20240831-095649_Via](https://github.com/user-attachments/assets/386b29af-1acf-429c-86be-02ec5903cdc5)

**Comment by WhiteSevs** [comment]
这个页面就是贴吧新的页面，触发方式不稳定，所以暂时无法兼容处理

**Comment by mpamxl** [comment]
> 这个页面就是贴吧新的页面，触发方式不稳定，所以暂时无法兼容处理

意思要再等等再看怎么处理吗？

**Comment by WhiteSevs** [comment]
新版贴吧帖子页面最近触发出现的很频繁了，新增了`帖内(uni-app)`

**Comment by mpamxl** [comment]
> 新版贴吧帖子页面最近触发出现的很频繁了，新增了`帖内(uni-app)`

意思已经修复这个问题了吗？

**Comment by WhiteSevs** [comment]
准确点说是对这个页面适配了点功能，原版的帖子页面有些功能在这个新的帖子页面上还没有实现的方法

**Comment by mpamxl** [comment]
> 准确点说是对这个页面适配了点功能，原版的帖子页面有些功能在这个新的帖子页面上还没有实现的方法

就是说这个弹窗问题暂时还没解决？

**Comment by WhiteSevs** [comment]
你说的弹窗我没有遇到过

**Comment by mpamxl** [comment]
> 你说的弹窗我没有遇到过
点击http://static.tieba.baidu.com/f?kw=黄金太阳&ie=utf-8任意帖子都提示加载失败
