### ISSUE TITLE
[Bug] Greasy Fork 优化脚本设置显示异常

### ISSUE THREAD

**Issue by Lucas04-nhr** [WhiteSevs/TamperMonkeyScript#32]
### 先决条件

- [X] 我使用的是**本仓库**最新版本的油猴脚本
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**

### 脚本运行的容器

扩展-篡改猴（TamperMonkey）

### 扩展版本

5.3.2

### 脚本名称

GreasyFork优化

### 问题描述

打开脚本设置页中无法进行编辑，疑似CSS的遮罩层级没有处理对。
<img width="1680" alt="Snipaste_2024-11-16_10-01-39@2x" src="https://github.com/user-attachments/assets/8be5008f-d2a9-4742-b9ad-a5fe1803c8e3">

### 复现步骤

本机环境 macOS 15.1 Google Chrome 130 
在greasyfork.org打开脚本设置页即可复现。

**Comment by WhiteSevs** [comment]
你开控制台看看遮罩层和动画层的`z-index`层级

![PixPin_2024-11-16_11-37-29](https://github.com/user-attachments/assets/6dc9fd83-ed00-4993-8eff-43f18b908ac1)

**Comment by Lucas04-nhr** [comment]
<img width="479" alt="Snipaste_2024-11-16_11-41-42@2x" src="https://github.com/user-attachments/assets/aee65195-fdd1-4968-a752-33d7b91d422e">

**Comment by WhiteSevs** [comment]
应该是你页面有某个元素获取到的`z-index`太大了，你控制台执行下面的代码看看是哪个元素

```js

        let maxZIndex = 0;
        let maxZIndexNode = null;
        document.querySelectorAll("*").forEach((element,index) => {
            let nodeStyle = window.getComputedStyle(element);
            if (nodeStyle.position !== "static" && nodeStyle.display !== "none") {
                let nodeZIndex = parseInt(nodeStyle.zIndex);
                if(!isNaN(nodeZIndex)){
                    if(nodeZIndex>maxZIndex){
                        maxZIndex = nodeZIndex;
                        maxZIndexNode = element;
                    }
                }
            } 
        })
console.log(maxZIndex,maxZIndexNode);
```

**Comment by Lucas04-nhr** [comment]
刚刚试了一下，应该是 kimi AI 的网页插件导致的（

**Comment by WhiteSevs** [comment]
我待会调一下设置面板的`z-index`的最大层级应该就可以修复了
