### ISSUE TITLE
[Feature] <关于搜索药物时的建议>

### ISSUE THREAD

**Issue by BitsAstro** [WhiteSevs/TamperMonkeyScript#34]
### 先决条件

- [X] 我已经在[这里](https://github.com/WhiteSevs/TamperMonkeyScript/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**

### 脚本名称

【移动端】百度系优化

### 描述

![IMG_20241211_095002](https://github.com/user-attachments/assets/b4b36e8c-b686-47ac-850d-681abd87726e)
作者 提个建议
希望搜索药物时
能将红色圈内的内容保留，因为还是有点用的
对于了解药物信息来说，很方便
将绿色圈内的内容删除，没什么用，而且占地方

### 可能的解决方案

在开启了 “百度优化脚本时”
红色圈内的内容被删除了 希望保留
而绿色圈内的内容则希望删除

**Comment by WhiteSevs** [comment]
已移除屏蔽`百度医典`

下面的百度健康商城可以自行添加以下屏蔽规则用于屏蔽

```text
match-attr##srcid##med_mall_recommend_san
match-attr##srcid##med_wz
```

**Comment by BitsAstro** [comment]
效率很高，感谢作者大大！
