### ISSUE TITLE
关于百度系优化问题

### ISSUE THREAD

**Issue by e-tw** [WhiteSevs/TamperMonkeyScript#4]
### 先决条件

- [x] 我已经在[这里](https://github.com/WhiteSevs/TamperMonkeyScript/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**

### 描述

Hi,

关于百度系优化可否请你增加一个地方？ 贴吧楼中楼在不登入的状况下可以展开所有回复内容？

**Comment by WhiteSevs** [comment]
？
未限制需要登录才能查看楼中楼评论

**Comment by e-tw** [comment]
你好,可以了.
@WhiteSevs

**Comment by WhiteSevs** [comment]
> 你好:
> 这个部分能一并支援PC版本吗?
> 1.回复"点击查看"会跳出登入画面2.进入P2后好像一些回复内容会看不到.
> @WhiteSevs 

不考虑，因为这个是移动端的百度系优化，或许以后可能写个PC端贴吧专用的

**Comment by e-tw** [comment]
ok
