### ISSUE TITLE
[Feature] <抖音网页版>移动端和电脑端优化，跳过广告，优化显示

### ISSUE THREAD

**Issue by androidcn** [WhiteSevs/TamperMonkeyScript#5]
### 先决条件

- [X] 我已经在[这里](https://github.com/WhiteSevs/TamperMonkeyScript/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**

### 描述

[Feature] <抖音网页版>移动端和电脑端优化，跳过广告，优化显示

**Comment by WhiteSevs** [comment]
已创建

**Comment by androidcn** [comment]
> 已创建

谢谢优秀的开发者。!
还有一些  客户端的 提示 下载  信息 其实也可以隐藏掉！

**Comment by WhiteSevs** [comment]
附上截图，不知道你说的是哪个地方的

**Comment by androidcn** [comment]
> 附上截图，不知道你说的是哪个地方的

我记得有几处客户端提醒，这里是一个

![image](https://github.com/WhiteSevs/TamperMonkeyScript/assets/271715/8fcab72e-4f6e-4fd1-94f4-240d5ca32277)

1.搜索框的广告 选择性 打开
2.搜索框下方的 抖音热点和猜你所想 可以选择性 隐藏

感谢

![image](https://github.com/WhiteSevs/TamperMonkeyScript/assets/271715/e1b94976-d10f-400b-947d-e8371c61f004)

**Comment by androidcn** [comment]
![image](https://github.com/WhiteSevs/TamperMonkeyScript/assets/271715/866afd42-f333-4aa2-bdde-a91b8766e41b)

还有这三个按钮

**Comment by WhiteSevs** [comment]
已添加具体的设置

**Comment by androidcn** [comment]
> 已添加相关的设置

哥们太牛了！页面如果能再加一个方便弹出设置的按钮就更好了！感谢感谢

**Comment by WhiteSevs** [comment]
不考虑在页面添加设置按钮，在油猴菜单进去即可

**Comment by androidcn** [comment]
> 不考虑在页面添加设置按钮，在油猴菜单进去即可

好!

**Comment by loveuqian** [comment]
这个抖音脚本貌似 greasyfork 搜不到？坐着没有发布吗？

**Comment by androidcn** [comment]
> 这个抖音脚本貌似 greasyfork 搜不到？作者没有发布吗？
> 
> 

直接引用GitHub就好了…非要去gf吗？
