### ISSUE TITLE
可否将百度贴吧展开回复和去弹窗单独加到贴吧优化中？

### ISSUE THREAD

**Issue by mpamxl** [WhiteSevs/TamperMonkeyScript#6]
### 先决条件

- [x] #7

### 描述

因为百家号优化里面太多东西，而且有时会和别的自动展开之类功能重复，可否将贴吧部分的展开回复那些功能单独也放到贴吧优化那个脚本中？

**Comment by WhiteSevs** [comment]
描述的有点混乱，百家号优化和贴吧优化有啥关联？贴吧优化.use.js这个脚本里面已存在查看评论的功能
![Clip_2024-04-12_10-58-44](https://github.com/WhiteSevs/TamperMonkeyScript/assets/50544447/b182be5d-600d-4a79-a1e2-f4a0d642c186)

**Comment by mpamxl** [comment]
> 描述的有点混乱，百家号优化和贴吧优化有啥关联？[贴吧优化.use.js](https://github.com/WhiteSevs/TamperMonkeyScript/blob/0d367076930d3cedfd40359712778fe69daa5e8b/%E8%B4%B4%E5%90%A7%E4%BC%98%E5%8C%96/%E8%B4%B4%E5%90%A7%E4%BC%98%E5%8C%96.user.js)这个脚本里面已存在查看评论的功能
> ![Clip_2024-04-12_10-58-44](https://github.com/WhiteSevs/TamperMonkeyScript/assets/50544447/b182be5d-600d-4a79-a1e2-f4a0d642c186)
> 

贴吧优化这个脚本移动端没法自动展开回复和去掉那个打开APP查看更多的功能

**Comment by mpamxl** [comment]
我的意思是能否让贴吧优化这个脚本也有移动端的查看回复和去掉下载APP弹窗的功能

**Comment by WhiteSevs** [comment]
`贴吧优化`是PC端使用的，移动端的请使用`【移动端】百度系优化`

**Comment by mpamxl** [comment]
> `贴吧优化`是PC端使用的，移动端的请使用`【移动端】百度系优化`

所以我就是说这个问题，因为移动端你是把所有百家号功能都做在了一起，但比如别的插件也有百家号的某些功能，会有重复的情况，能否就把贴吧功能的部分移动端的也单独弄出来呢？

**Comment by WhiteSevs** [comment]
> > `贴吧优化`是PC端使用的，移动端的请使用`【移动端】百度系优化`
> 
> 所以我就是说这个问题，因为移动端你是把所有百家号功能都做在了一起，但比如别的插件也有百家号的某些功能，会有重复的情况，能否就把贴吧功能的部分移动端的也单独弄出来呢？

有重复的情况就设置那个域名禁止运行脚本

**Comment by mpamxl** [comment]
> > > `贴吧优化`是PC端使用的，移动端的请使用`【移动端】百度系优化`
> > 
> > 所以我就是说这个问题，因为移动端你是把所有百家号功能都做在了一起，但比如别的插件也有百家号的某些功能，会有重复的情况，能否就把贴吧功能的部分移动端的也单独弄出来呢？
> 
> 有重复的情况就设置那个域名禁止运行脚本`@exclude`或者只设置一个`@match`

好吧，我想着贴吧优化那个脚本，可以把电脑手机都覆盖了，为啥只电脑呢......这样不是更合理点

**Comment by WhiteSevs** [comment]
因为不是用typescript开发，代码都集中到单个文件内，且移动端和PC端的运行环境不好做区分

**Comment by mpamxl** [comment]
> 因为不是用typescript开发，代码都集中到单个文件内，且移动端和PC端的运行环境不好做区分

了解，那可否把贴吧也单独做个移动端的？毕竟现在移动端的贴吧脚本也没有更好用的

**Comment by WhiteSevs** [comment]
> > 因为不是用typescript开发，代码都集中到单个文件内，且移动端和PC端的运行环境不好做区分
> 
> 了解，那可否把贴吧也单独做个移动端的？毕竟现在移动端的贴吧脚本也没有更好用的

有这个需求可自行抽出贴吧的代码，目前贴吧这块没有需要更新的了

**Comment by mpamxl** [comment]
> > > 因为不是用typescript开发，代码都集中到单个文件内，且移动端和PC端的运行环境不好做区分
> > 
> > 了解，那可否把贴吧也单独做个移动端的？毕竟现在移动端的贴吧脚本也没有更好用的
> 
> 有这个需求可自行抽出贴吧的代码，目前贴吧这块没有需要更新的了

其实有想过自己抽出，但整个太长了，有些没注释的地方不太会，怕搞错，所以想着作者自己写的比较清楚方便的话可以抽取这部分下

**Comment by WhiteSevs** [comment]
https://github.com/WhiteSevs/TamperMonkeyScript/blob/22586d61cc4c03711e8688f554b0a0e17a5ed7a6/%E3%80%90%E7%A7%BB%E5%8A%A8%E7%AB%AF%E3%80%91%E7%99%BE%E5%BA%A6%E7%B3%BB%E4%BC%98%E5%8C%96/%E3%80%90%E7%A7%BB%E5%8A%A8%E7%AB%AF%E3%80%91%E7%99%BE%E5%BA%A6%E7%B3%BB%E4%BC%98%E5%8C%96.user.js#L538-L564

留个`this.tieba()`就行了

**Comment by mpamxl** [comment]
[贴吧优化3.txt](https://github.com/WhiteSevs/TamperMonkeyScript/files/14957137/3.txt)
我提取了下里面的部分，麻烦大佬帮看下有没遗漏或者没有清理干净的地方可以嘛？

**Comment by mpamxl** [comment]
有几个劫持的注释是全局或者不太清楚的地方我不确定，所以麻烦下大佬有空的话帮看看

**Comment by mpamxl** [comment]
好的，还有个问题，贴吧点签到提示user have no real name

**Comment by mpamxl** [comment]
> > 好的，还有个问题，贴吧点签到提示user have no real name
> 
> 套壳浏览器的问题，没有携带cookie

还有就是贴吧有些会跳转static.tieba.baidu.com，这个会无效，可以适配吗？

**Comment by WhiteSevs** [comment]
> > > 好的，还有个问题，贴吧点签到提示user have no real name
> > 
> > 
> > 套壳浏览器的问题，没有携带cookie
> 
> 还有就是贴吧有些会跳转static.tieba.baidu.com，这个会无效，可以适配吗？

其它问题请重新开issue
