### ISSUE TITLE
小红书脚本获取评论不全

### ISSUE THREAD

**Issue by mpamxl** [WhiteSevs/TamperMonkeyScript#9]
### 先决条件

- [X] 我使用的是**本仓库**最新版本的油猴脚本
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**

### 脚本运行的容器

Via浏览器

### 脚本名称

【移动端】小红书优化

### 问题描述

获取评论只有两三个，剩下的都无法获取，求修复

**Comment by WhiteSevs** [comment]
需要登录才能查看更多评论

**Comment by mpamxl** [comment]
> 需要登录才能查看更多评论

可比如百度搜索打开某小红书内容页并没有登录按钮

**Comment by WhiteSevs** [comment]
需要切换UA到电脑进行登录

**Comment by mpamxl** [comment]
> 需要切换UA到电脑进行登录

OK，感觉对移动端还是有点麻烦

**Comment by WhiteSevs** [comment]
> > 需要切换UA到电脑进行登录
> 
> OK，感觉对移动端还是有点麻烦


小红书没给手机浏览器做登录界面，只能这样
